### ISSUE TITLE
Is this the UC Davis project?

### ISSUE THREAD

**Issue by jake653** [hahnicity/apl#3]
Hi Gregory
It there an active public access server?
as described in:
An Analytic Platform for the Rapid and Reproducible Annotation of Ventilator Waveform.
 We were previously looking at VentMAP as a model for real time annotation in a Ventilator OS-GUI (using something like the $99 NVIDIA Jetson Nano)
 Is APL providing a similar set of functions?

Thanks...

**Comment by hahnicity** [comment]
Hi,

There is no public access server unfortunately. APL could be used for real time annotation, although we have currently only developed it as a retrospective annotation server. Adding real time capability will take additional work. It may not be worth it if you want something quick and dirty. But if you're trying to create a long living software project then maybe.

If you want to code something up on your own I would suggest looking at some of the graphing code from `source/templates/apgraph.html`. We spent a bit of work on it and it handles all the UI aspects of our server.

Greg
